name: janrakshak
description: "flood_monitor_app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core Services and Authentication
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.3.0
  supabase_flutter: ^2.10.2

  # UI/Style Dependencies
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0 # For rich icons

  # State Management & Routing
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^12.1.1

  # Charts/Maps (for Dashboard/Predictions)
  fl_chart: ^0.65.0
  # google_maps_flutter: ^2.5.0
  # flutter_map: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/